server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/survey?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1
  jpa:
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB