server:
  port: 8080
spring:
  datasource:
    #로컬용
    url: jdbc:mysql://localhost:3306/survey?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1073031560a!
    #url: jdbc:mysql://localhost:3306/survey?useSSL=false&allowPublicKeyRetrieval=true
    #username: choys0199
    #password: 1073031560a!
  jpa:
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB