server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/survey?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1073031560a!
  jpa:
    defer-datasource-initialization: true